### ISSUE TITLE
TFTP load error

### ISSUE THREAD

**Issue by jimmy89628** [pftf/RPi3#11]
when is load debug version，got an error：
Loading driver at 0x00036ECA000 EntryPoint=0x00036ED1D48 tftpDynamicCommand.efi
InstallProtocolInterface: BC62157E-3E33-4FEC-9920-2D3B36D750DF 35BC1918
InstallProtocolInterface: 6A1EE763-D47A-43B4-AABE-EF1DE2AB56FC 36ED6070
ProtectUefiImageCommon - 0x35BC13C0
  - 0x0000000036ECA000 - 0x000000000000F000
SetUefiImageMemoryAttributes - 0x0000000036ECA000 - 0x0000000000001000 (0x0000000000004008)
SetUefiImageMemoryAttributes - 0x0000000036ECB000 - 0x000000000000A000 (0x0000000000020008)
SetUefiImageMemoryAttributes - 0x0000000036ED5000 - 0x0000000000004000 (0x0000000000004008)
Status: 0x0000000E

ASSERT_EFI_ERROR (Status = Not Found)
/TftpDynamicCommand/TftpDynamicCommand/DEBUG/AutoGen.c(520): !EFI_ERROR (Status)

How to fix this？thank u

**Comment by pbatard** [comment]
Should be fixed with latest build. If you still see the issue, let us know.
