### ISSUE TITLE
Stuck at "Graphics Console Started"

### ISSUE THREAD

**Issue by ghost** [pftf/RPi3#12]
I compiled it from scratch as DEBUG version, and I prepared RPI_EFI.fd and other dependencies on a FAT32 partiton of USB-HDD. When I plugged it onto USB port and powered it on, it just gave me a screen which says "Graphics Console Started", and it does not response any keyboard input. What's the issue and how to solve it?

**Comment by pbatard** [comment]
> how to solve it?

Get a serial console set up, and you'll know. It's very easy to get serial output on the Pi, and if you are actually serious about compiling your own firmware, the first thing you should do is set up a serial console.

Unless you are experiencing an issue with the firmwares we release, I'm afraid that your custom compilation is not really an issue we want to investigate, so I will close this issue now.
