### ISSUE TITLE
Improve SDhost driver to fail gracefully when no card is present

### ISSUE THREAD

**Issue by andreiw** [pftf/RPi3#14]
Booting UEFI from USB or network still requires an SD card, because the SDhost driver will loop forever on I/O errors. Unfortunately the Pi Foundation didn't wire up the card detect pin so we have to do something more creative.

**Comment by MagicRB** [comment]
A stupid solution would be try 200 or so times and then assume no card there

**Comment by andreiw** [comment]
something like that, yeah

**Comment by ehem** [comment]
The log in pftf/RPi4#77 seems interesting.  Notably that consistent "ERRI MmcStatus 0x18040" being an indicator of card absent.  The alternative which comes to mind is adding something to the command-line to tell it to skip trying MMC.

**Comment by MagicRB** [comment]
I kind of maybe unrelated question, but from what I had gathered the in-CPU bootloader only looks for stuff to boot on the sdcard, so how can you get this UEFI bios running, without an sdcard?

**Comment by pbatard** [comment]
> the in-CPU bootloader only looks for stuff to boot on the sdcard

That is not the case. The Pi 3 and Pi 4 on-die bootloader code is able to perform a lookup for boot files that reside on a USB drive. If you use a recent EEPROM with a recent `start4.elf`, you will get straight to USB boot.

**Comment by MagicRB** [comment]
cool, i thought it didn't do that, you learn something new everyday ain't that right?
