### ISSUE TITLE
Installing over serial console

### ISSUE THREAD

**Issue by carlosedp** [pftf/RPi3#9]
Hi Pete, I've followed your post (https://pete.akeo.ie/2019/07/installing-debian-arm64-on-raspberry-pi.html) and created the SDcard with Debian10 and Firmware files version 1.17 and to be able to install it over the serial console, the following must be done:

* When GRUB menu opens, hit "e" 
* Replace `--- quiet` by `--- console=ttyS0,115200n8`
* Hit Ctrl-x to boot

Maybe it's a good addition to the post.

**Comment by pbatard** [comment]
I'm going to close this issue. I'm not trying to cover every use case in the blog post and I would assert that people interested in installing through serial should be able to figure things on their own (especially as I do make some mention of post-install GRUB serial config). They should also be able to find this issue.
